name: Node.js CI Backend tests

on:
  push:
defaults:
  run:
    working-directory: backend
env:
  NODE_ENV: test
jobs:
  buildStepJob:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        node-version: [ 18.x ]
        mongodb-version: [ '5.0' ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} and install packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install pm2 global
        run: npm install pm2@latest -g
      - name: Create .env file
        run: |
          touch .env.test.local
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env.test.local
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test.local
          echo "PORT=${{ secrets.PORT }}" >> .env.test.local
          echo "NODE_ENV=test" >> .env.test.local
      - name: Install dependencies
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Test backend
        run: pm2 start ecosystem.config.cjs --env test && npm run test && pm2 stop ecosystem.config.cjs